language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8
env:
  matrix:
  - TERM=dumb
  global:
  - GRADLE_OPTS="-Xms128m -Xmx6g -Xss512k"
  - MALLOC_ARENA_MAX=2
  - CI_NAME=travis-ci
  - secure: dz8FVLtE8hXYAhrMcBoYJh6iDbfm8V231eqLF4uWVeEDptf5iEvE58YqyDp9MW/XSo2KpWHdd8CkGK/auMrr6gAOTUY4woIDncdzGcnTTQQPJXVgdXjdilEwFrzEdTR64wkusBA924u47JOQnAXQTrhD0kZYD6ckcW9Bw4gg74s=
  - secure: CuqvnSiDcMGB7AxaFBq82zXuh+PwZ2nfcD+Y3AI38H3Hj9EdEwqrpkSaSrxPIvoShe7YgCtUqc/ELNuU7IeocosxJP6aA3Rd5fsSc4IHbWTER0+EnqepiDaDjIttvA9WnUwSypeN5lkdaT0yqUCI1j5FuGus+o4liq7n/4IXAlw=
before_install:
- chmod +x gradlew
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
before_script:
- sudo service docker stop || true
- sudo service elasticsearch stop || true
- sudo service memcached stop || true
- sudo service mysql stop || true
- sudo service neo4j stop || true
- sudo service postgresql stop || true
- sudo service redis-server stop || true
- sudo service rsync stop || true
- sudo service x11-common stop || true
- ps -e -o pid,vsz,comm= | sort -n -k 2
- sudo free -m -t
script:
- ./gradlew test --no-daemon
after_success:
- "./gradlew jacocoRootReport coveralls"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
addons:
  coverity_scan:
    project:
      name: CalebFenton/simplify
      description: Build submitted via Travis CI
    notification_email: calebjfenton@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: coverity_scan
